const $=x=>document.getElementById(x),stage=$("stage"),cv=$("base"),ctx=cv.getContext("2d"),layers=$("layers");let img=null,original=null,sel=null,scale=1,showRef=false;
function st(t){$("status").textContent=t}function pick(e){document.querySelectorAll(".layer").forEach(x=>x.classList.remove("active"));sel=e;if(e){e.classList.add("active");$("text").value=e.innerText;$("size").value=parseInt(getComputedStyle(e).fontSize)||20}}
function drag(e){let a=0,sx,sy,l,t;e.onpointerdown=v=>{pick(e);a=1;sx=v.clientX;sy=v.clientY;l=e.offsetLeft;t=e.offsetTop;e.setPointerCapture(v.pointerId)};e.onpointermove=v=>{if(a){e.style.left=Math.max(0,l+v.clientX-sx)+"px";e.style.top=Math.max(0,t+v.clientY-sy)+"px"}};e.onpointerup=()=>a=0}
function add(v,b){let e=document.createElement("div");e.className="layer";e.contentEditable=true;e.innerText=v;e.style.left=b.x0*scale+"px";e.style.top=b.y0*scale+"px";e.style.fontSize=Math.max(9,(b.y1-b.y0)*scale*.8)+"px";layers.appendChild(e);drag(e)}
function paint(){ctx.clearRect(0,0,cv.width,cv.height);ctx.drawImage(img,0,0,cv.width,cv.height)}
function clean(b){let x=Math.max(0,Math.floor(b.x0*scale)-2),y=Math.max(0,Math.floor(b.y0*scale)-2),w=Math.min(cv.width-x,Math.ceil((b.x1-b.x0)*scale)+4),h=Math.min(cv.height-y,Math.ceil((b.y1-b.y0)*scale)+4);let sx=Math.max(0,x-3),sy=Math.max(0,y+Math.floor(h/2));try{let p=ctx.getImageData(sx,sy,1,1).data;ctx.fillStyle="rgb("+p[0]+","+p[1]+","+p[2]+")";ctx.fillRect(x,y,w,h)}catch(_){}}
$("file").onchange=e=>{let f=e.target.files[0];if(!f)return,r=new FileReader();r.onload=()=>{img=new Image();img.onload=()=>{scale=Math.min(1,900/img.width);cv.width=Math.round(img.width*scale);cv.height=Math.round(img.height*scale);stage.style.width=cv.width+"px";stage.style.height=cv.height+"px";original=r.result;paint();layers.innerHTML="";st("Image loaded. Analyze & Reconstruct दबाएँ।")};img.src=r.result};r.readAsDataURL(f)};
$("analyze").onclick=async()=>{if(!img)return alert("पहले image upload करें");$("err").textContent="";layers.innerHTML="";paint();st("AI OCR और layout analyze हो रहा है…");try{let r=await Tesseract.recognize(original,"eng",{logger:m=>{if(m.status==="recognizing text")st("Analyzing "+Math.round(m.progress*100)+"%")}}),words=r.data.words||[];if(!words.length&&r.data.blocks)for(const b of r.data.blocks)for(const p of b.paragraphs||[])for(const l of p.lines||[])for(const w of l.words||[])words.push(w);let good=words.filter(w=>w.text&&w.text.trim()&&w.bbox&&+(w.confidence??100)>35);good.forEach(w=>clean(w.bbox));good.forEach(w=>add(w.text.trim(),w.bbox));st("Reconstructed: "+good.length+" editable text elements. Original Reference से compare करें।")}catch(e){$("err").textContent=e.message||String(e);st("Analyze failed")}};
$("reference").onclick=()=>{if(!img)return;showRef=!showRef;if(showRef){paint();layers.style.display="none";$("reference").textContent="Show Reconstructed"}else{paint();let els=[...document.querySelectorAll(".layer")];els.forEach(e=>{let b={x0:e.offsetLeft/scale,y0:e.offsetTop/scale,x1:(e.offsetLeft+e.offsetWidth)/scale,y1:(e.offsetTop+e.offsetHeight)/scale};clean(b)});layers.style.display="block";$("reference").textContent="Original Reference"}};
$("text").oninput=()=>{if(sel)sel.innerText=$("text").value};$("size").oninput=()=>{if(sel)sel.style.fontSize=$("size").value+"px"};$("color").oninput=()=>{if(sel)sel.style.color=$("color").value};$("del").onclick=()=>{if(sel){sel.remove();sel=null}};