const $=x=>document.getElementById(x),stage=$("stage");let src=null,selected=null,bg=true;
function status(t,p){$("status").textContent=t;if(p!==undefined)$("bar").style.width=p+"%"}
function select(el){document.querySelectorAll(".layer").forEach(x=>x.classList.remove("active"));selected=el;if(!el)return;el.classList.add("active");$("editText").value=el.innerText;$("fontSize").value=parseInt(getComputedStyle(el).fontSize)||20}
function makeText(v,x,y,size){let el=document.createElement("div");el.className="layer";el.contentEditable="true";el.innerText=v;el.style.left=x+"px";el.style.top=y+"px";el.style.fontSize=size+"px";el.style.color="#111";stage.appendChild(el);drag(el);return el}
function drag(el){let active=false,sx=0,sy=0,l=0,t=0;el.addEventListener("pointerdown",e=>{select(el);active=true;sx=e.clientX;sy=e.clientY;l=el.offsetLeft;t=el.offsetTop;el.setPointerCapture(e.pointerId)});el.addEventListener("pointermove",e=>{if(active){el.style.left=Math.max(0,l+e.clientX-sx)+"px";el.style.top=Math.max(0,t+e.clientY-sy)+"px"}});el.addEventListener("pointerup",()=>active=false)}
$("file").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;$("error").textContent="";const r=new FileReader();r.onload=()=>{src=r.result;const im=new Image();im.onload=()=>{const sc=Math.min(1,900/im.naturalWidth);stage.dataset.scale=sc;stage.style.width=im.naturalWidth*sc+"px";stage.style.height=im.naturalHeight*sc+"px";stage.style.backgroundImage=`url("${src}")`;stage.innerHTML="";bg=true;status("Image loaded. अब Analyze & Convert दबाएँ।",0)};im.onerror=()=>status("Image पढ़ी नहीं जा सकी।",0);im.src=src};r.readAsDataURL(f)});
$("analyze").addEventListener("click",async()=>{if(!src){alert("पहले image select करें");return}if(!window.Tesseract){$("error").textContent="OCR library load नहीं हुई। Internet/CDN connection check करें।";return}stage.innerHTML="";$("error").textContent="";status("OCR engine loading…",3);try{const result=await Tesseract.recognize(src,"eng",{logger:m=>{if(m.status==="recognizing text")status("Analyzing text… "+Math.round(m.progress*100)+"%",Math.round(m.progress*100));else status(m.status||"Processing…")}});const sc=Number(stage.dataset.scale)||1;let words=[];
if(result.data&&Array.isArray(result.data.words))words=result.data.words;
else if(result.data&&Array.isArray(result.data.blocks)){for(const b of result.data.blocks||[])for(const p of b.paragraphs||[])for(const l of p.lines||[])for(const w of l.words||[])words.push(w)}
let n=0;for(const w of words){const tx=(w.text||"").trim(),conf=Number(w.confidence??w.conf??100),b=w.bbox;if(!tx||!b||conf<30)continue;const fs=Math.max(9,Math.round((b.y1-b.y0)*sc*.82));makeText(tx,b.x0*sc,b.y0*sc,fs);n++}
if(!n&&result.data&&result.data.text){makeText(result.data.text.trim(),20,20,18);n=1}
status("Done — "+n+" editable text layer(s) बने।",100)}catch(err){console.error(err);$("error").textContent="Error: "+(err&&err.message?err.message:String(err));status("Analyze failed — नीचे error देखें।",0)}});
$("addText").onclick=()=>select(makeText("Editable Text",20,20,20));$("toggleBg").onclick=()=>{bg=!bg;stage.style.backgroundImage=bg&&src?`url("${src}")`:"none"};$("editText").oninput=()=>{if(selected)selected.innerText=$("editText").value};$("fontSize").oninput=()=>{if(selected)selected.style.fontSize=$("fontSize").value+"px"};$("color").oninput=()=>{if(selected)selected.style.color=$("color").value};$("remove").onclick=()=>{if(selected){selected.remove();selected=null}};